Add xdp-synproxy to bpf-examples
xdp-project/bpf-examples pull request #103
Opened 2023-10-04 20:15 UTC by vincentmli

this code is from kernel bpf selftests xdp synproxy, removed the tc part for simplicity, shows an exmaple of using libxdp to attach xdp synproxy program on network interface.

if port is not in allowed ports, the packet will be dropped by xdp synproxy by default, this would break tcp connections to ports that user does not want to do synproxy, change the default to allow connection pass through.

2023-10-04 20:17 UTC, vincentmli commented
Hi @tohojo:

Here is the PR to add xdp-synproxy to bpf-examples repo, please review :)

2023-10-16 15:44 UTC, vincentmli commented
Hi @tohojo do you have time to review this PR? :)

2023-10-17 12:46 UTC, tohojo requested changes

2023-10-17 12:46 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +		{ "file", required_argument, NULL, 'f' },
Is supplying the filename on the command line really a good idea? Seems a bit cumbersome, and since there's no checks on the supplied objects, things can quickly get out of sync...

2023-10-17 12:46 UTC, tohojo commented on xdp-synproxy/xdp_synproxy_kern.c
> +					   struct header_pointers *hdr, bool xdp)
The `xdp` arg seems to be leftover from the in-kernel version that also supports TC? Let's just get rid of that...

2023-10-17 12:46 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +		progname);
So the command line interface seems a little strange to me. It attaches on the first run, but you can also supply a prog ID to replace the ports and options while it's running? But the only way to detach is to kill the original instance? IDK, maybe this is fine for an initial version, since we're just porting this over from the selftests...

2023-10-17 15:34 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +		{ "file", required_argument, NULL, 'f' },
the in kernel version search the object file, my reasoning is this allow user to specify whatever location user prefer to put the object file in to give user the flexibility, also when run in container or in k8s as daemonset, this allow user to customize the object file location to fit their container environment. I will add check to see if the file exist in location that is specified by the argument, how does that sound?

2023-10-17 15:34 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy_kern.c
> +					   struct header_pointers *hdr, bool xdp)
ok, got it

2023-10-17 15:39 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +		progname);
as an initial version and to simplify, I will just remove the prog ID argument. I think the original version intention is to have some kind of map persistency for the generated syncookie counter, so each time when the program is re-loaded/attached, the counter is not reset to 0, and probably as you pointed out to reconfigure ports and options maybe.

2023-10-19 09:57 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +		progname);
Sure, let's just keep it this way for now...

2023-10-25 14:15 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +		{ "file", required_argument, NULL, 'f' },
ah, I think I got it, let me know otherwise :)

```
diff --git a/xdp-synproxy/xdp_synproxy.c b/xdp-synproxy/xdp_synproxy.c
index ed073c1..18390f3 100644
--- a/xdp-synproxy/xdp_synproxy.c
+++ b/xdp-synproxy/xdp_synproxy.c
@@ -167,9 +167,11 @@ static int syncookie_attach(char *file, unsigned int ifindex)
        int err;
 
        char *xdp_filename = file;
+       char *xdp_program_name = "syncookie_xdp";
        DECLARE_LIBXDP_OPTS(xdp_program_opts, xdp_opts, 0);
 
        xdp_opts.open_filename = xdp_filename;
+       xdp_opts.prog_name = xdp_program_name;
        p = xdp_program__create(&xdp_opts);
        err = libxdp_get_error(p);
        if (err) {
```

2023-10-25 14:46 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +		{ "file", required_argument, NULL, 'f' },
Yup, exactly :)

2023-10-25 18:00 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +		{ "file", required_argument, NULL, 'f' },
thanks! pushed the new change.

2023-10-26 01:30 UTC, vincentmli commented
@tohojo I like your idea of using skeleton to save the user space program from loading external object file, so I updated the code with initial skeleton changes, the code could still be optimized like the map access through skeleton, maybe we save that for next revision and get this example in first, what do you think?

2023-10-26 09:17 UTC, tohojo requested changes
A few error path nits

2023-10-26 09:17 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +		return err;
This needs to close the skeleton; probably a second error label at the bottom is easiest?

2023-10-26 09:17 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +                p = NULL;
This should be an xdp_program__close().

2023-10-26 09:17 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +                p = NULL;
(Or just call close before checking `err`)

2023-10-26 13:26 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +                p = NULL;
pushed the change, hope I did not miss anything :)

2023-10-26 14:08 UTC, tohojo requested changes
Not sure if it's the Github review interface making things up, but no, that was not the fix I had in mind :)

2023-10-26 14:08 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +                p = NULL;
You didn't fix this one...

2023-10-26 14:08 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +		xdp_program__close(p);
Instead you moved this one so there's now no xdp_program__close on the success path...

2023-10-26 16:28 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +		xdp_program__close(p);
sorry for my misunderstanding, do we need xdp_program__close on success path (err == 0) ?  if the program is attached successfully, xdp_program__close will not cause the program to be detached?

2023-10-26 16:42 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +		xdp_program__close(p);
sorry I am not clear on the skeleton destroy and program fd close imapct, so let me ask this to clarify  or if you could explain a little bit on the reason :)

1, if program is attached successfully
a, skeleton need to be destroyed ?
b, program fd needed to be closed?
if both yes, why?

2, if program is not attached successfully,
a, program fd needed to be closed first? yes
b, skeleton need to be destroyed ? yes

am I correct?

2023-10-26 16:53 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +                p = NULL;
you were talking about code in cleanup here, and I am fixing code at syncookie_attatch, my bad :)

2023-10-26 16:59 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +                p = NULL;
so the cleanup triggered after successful attach, but when SIGINT/SIGTERM is received, program is detached, if the detach failed, we xdp_program__close before checking the error message, correct? do we need to destroy the skeletion in cleanup?

2023-10-26 17:27 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +                p = NULL;
I likely may still miss something, let me try again with this, so regardless if the program is detached successfully or not, the xdp program will be closed

```
diff --git a/xdp-synproxy/xdp_synproxy.c b/xdp-synproxy/xdp_synproxy.c
index 821608b..8183951 100644
--- a/xdp-synproxy/xdp_synproxy.c
+++ b/xdp-synproxy/xdp_synproxy.c
@@ -40,13 +40,14 @@ static noreturn void cleanup()
 
        err = xdp_program__detach(p, ifindex, 0, 0);
         if (err) {
+               xdp_program__close(p);
                libxdp_strerror(err, errmsg, sizeof(errmsg));
-                pr_warn("Couldn't attach BPF program: %s(%d)\n", errmsg, err);
+                pr_warn("Couldn't detach BPF program: %s(%d)\n", errmsg, err);
                 p = NULL;
-                exit(1);
+               exit(1);
         }
-       xdp_program__close(p);
 
+       xdp_program__close(p);
        exit(0);
 }
```

2023-10-26 18:21 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +		xdp_program__close(p);
you commented for cleanup, I missed it

2023-10-26 18:37 UTC, tohojo requested changes

2023-10-26 18:37 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +		xdp_program__close(p);
But the xdp_program__close() was already below the out label, so the goto below took care of that.

2023-10-26 18:37 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +	return err;
Drop this return, we want the success path to also run the cleanup functions below.

2023-10-26 18:37 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +                p = NULL;
Yes, Every xdp_prog pointer needs to be passed to xdp_program__close() before exiting, regardless of whether it's going through an error path or a success path. Same thing with the skeleton, when created, it needs to be destroyed properly again.

There is no side effect to the xdp_program__close(), the program is only detached by an explicit xdp_program__detach().

2023-10-26 18:37 UTC, tohojo commented on xdp-synproxy/xdp_synproxy.c
> +		xdp_program__close(p);
So what I meant was that you can combine the out path, so you change the end of the function, to be like:

```c
out_close:
    xdp_program__close(p);
out:
    xdp_synproxy_kern__destroy();
    return err;
```

and the you change this `goto out` below to be `goto out_close`. That way you hit both cleanup functions if the attach fails, and also in the success path below (if you get rid of the first return, see comment below).

2023-10-26 19:02 UTC, vincentmli commented
could not comment on your comment from github, you cleared confusion 

"
Yes, Every xdp_prog pointer needs to be passed to xdp_program__close() before exiting, regardless of whether it's going through an error path or a success path. Same thing with the skeleton, when created, it needs to be destroyed properly again.

There is no side effect to the xdp_program__close(), the program is only detached by an explicit xdp_program__detach()."

should skeleton also be destroyed after program attachment, regardless if the attachment succeeded or not?  I pushed the change, bare with me, we are getting closer

2023-10-26 19:26 UTC, vincentmli commented on xdp-synproxy/xdp_synproxy.c
> +		xdp_program__close(p);
my new change combined close and destroy into one same out label, I removed the return.

2023-10-26 19:30 UTC, vincentmli commented
so xdp_program and skeleton are sort of preparation resources for program attachment, after program attachment, regardless  attachment success or not, the xdp_program and skeleton are no longer needed and can be freed/destroyed, am I understanding it correct ?

2023-10-26 19:31 UTC, tohojo commented
Yup, Those data structures are for keeping the userspace data around, and once the program has been loaded into the kernel we no longer need them (since we're not using the skeleton for accessing the maps).

2023-10-26 19:32 UTC, tohojo approved these changes
Looks like we got all the combinations of error and success paths covered now :)

2023-10-26 19:33 UTC, merged