Added an eBPF Qdisc classifier example
xdp-project/bpf-examples pull request #15
Opened 2021-03-14 17:36 UTC by freysteinn

This example demonstrates how to write a simple eBPF Qdisc classifier
that classifies flows depending on their TCP port. The example comes
with two scripts, run-u32.sh and run-bpf.sh. Both scripts implement the
same functionality to make it easy to compare them. The scripts both
create two network namespaces called Left and Right, representing two
different hosts. The Left namespace loads a Qdisc classifier that rate
limits depending on the destination TCP port. It also starts iperf3
clients that connect to the Right namespace's iperf3 servers to
demonstrate the rate-limiting. The Qdisc classifiers give TCP ports 8080
and 8081 a high rate limit, while TCP port 8082 represents all other
traffic capped at 20 Mbps.

Signed-off-by: Frey Alfredsson <freysteinn@freysteinn.com>

2021-03-15 12:23 UTC, tohojo requested changes
Found a few nits, but otherwise looks good :)

2021-03-15 12:23 UTC, tohojo commented on bpf-filter/filter.c
> +	switch (bpf_ntohs(tcphdr->dest)) {
This incurs a runtime conversion - better to match on the raw header field and use bpf_htons() on the cases...

2021-03-15 12:23 UTC, tohojo commented on bpf-filter/run-bpf.sh
> +		bpf obj filter.o classid 1: direct-action
This is the only thing that is different between the two scripts - so do we really need two? Just passing 'bpf' or 'u32' as an argument to the script and varying the filter setup based on that would save the duplication...

2021-03-15 12:30 UTC, freysteinn commented on bpf-filter/run-bpf.sh
> +		bpf obj filter.o classid 1: direct-action
You are right. I will merge the scripts and add parameters.

2021-03-15 12:33 UTC, freysteinn commented on bpf-filter/filter.c
> +	switch (bpf_ntohs(tcphdr->dest)) {
That makes sense. I will change that and send in a new pull-request.

2021-03-15 12:40 UTC, tohojo commented
Frey Alfredsson ***@***.***> writes:

> @freysteinn commented on this pull request.
>
>
>
>> +	}
> +	else if (eth_type == bpf_htons(ETH_P_IPV6)) {
> +		ip_type = parse_ip6hdr(&nh, data_end, &ipv6hdr);
> +		if (ip_type != IPPROTO_TCP)
> +			goto out;
> +	} else {
> +		goto out;
> +	}
> +
> +	/* Classify TCP ports 8080 and 8081 */
> +	tcp_type = parse_tcphdr(&nh, data_end, &tcphdr);
> +	if (tcphdr + 1 > data_end) {
> +		goto out;
> +	}
> +
> +	switch (bpf_ntohs(tcphdr->dest)) {
>
> That makes sense. I will change that and send in a new pull-request.

If you just force-push to the branch this PR will update itself :)

2021-03-15 12:52 UTC, freysteinn commented
> Frey Alfredsson ***@***.***> writes:
> @freysteinn commented on this pull request. > + } + else if (eth_type == bpf_htons(ETH_P_IPV6)) { + ip_type = parse_ip6hdr(&nh, data_end, &ipv6hdr); + if (ip_type != IPPROTO_TCP) + goto out; + } else { + goto out; + } + + /* Classify TCP ports 8080 and 8081 */ + tcp_type = parse_tcphdr(&nh, data_end, &tcphdr); + if (tcphdr + 1 > data_end) { + goto out; + } + + switch (bpf_ntohs(tcphdr->dest)) { That makes sense. I will change that and send in a new pull-request.
> If you just force-push to the branch this PR will update itself :)

Excellent, I will do that :)

2021-03-15 14:14 UTC, netoptimizer commented
I find the directory name 'bpf-filter' misleading.

2021-03-15 14:44 UTC, tohojo commented
Jesper Dangaard Brouer ***@***.***> writes:

> I find the directory name 'bpf-filter' misleading.

Good point, didn't even notice that :)

Maybe 'tc-bpf-basic' or something like that instead?

2021-03-15 15:06 UTC, freysteinn commented
Yes, that's a good point.
I think tc-bpf-basic sounds good. However, if we later create an example that uses actions instead, would it be better to call it tc-bpf-basic-classifier? What do you think?

2021-03-15 15:16 UTC, tohojo commented
Frey Alfredsson ***@***.***> writes:

> Yes, that's a good point.
> I think tc-bpf-basic sounds good. However, if we later create an
> example that uses actions instead, would it be better to call it
> tc-bpf-basic-classifier? What do you think?

Sure, makes sense; or maybe drop 'bpf', and just go with
'tc-basic-classifier' ('bpf' is in the repo name, after all)

2021-03-17 00:13 UTC, tohojo requested changes
A few more nits :)

2021-03-17 00:13 UTC, tohojo commented on tc-basic-classifier/filter.c
> +	case bpf_ntohs(8080):
This should be bpf_htons()

2021-03-17 00:13 UTC, tohojo commented on tc-basic-classifier/filter.c
> +	case bpf_ntohs(8081):
And this as well

2021-03-17 00:13 UTC, tohojo commented on tc-basic-classifier/runner.sh
> +#set -o errexit
?

2021-03-17 00:21 UTC, freysteinn commented on tc-basic-classifier/runner.sh
> +#set -o errexit
Ahh, I was debugging an error related to the $1 variable not being set when I had no parameters. I forgot to remove the comment

2021-03-17 00:25 UTC, freysteinn commented on tc-basic-classifier/filter.c
> +	case bpf_ntohs(8081):
Of course. I blindly took the previous call and moved it. Unfortunately, it didn't fail, and therefore I didn't think much of it

2021-03-17 10:03 UTC, tohojo commented on tc-basic-classifier/runner.sh
> +#set -o errexit
Thought that might be the case :)

2021-03-17 10:04 UTC, tohojo commented on tc-basic-classifier/filter.c
> +	case bpf_ntohs(8081):
Yup, figured - and those 'h' and 'n's do look way too much like each other ;)

2021-03-17 10:04 UTC, tohojo approved these changes
Right, LGTM :)

2021-03-17 10:04 UTC, merged