Pping better output
xdp-project/bpf-examples pull request #16
Opened 2021-04-30 10:48 UTC by simosund

These commits update the standard output format to be equivalent with Kathie's pping standard format, which means it adds a timestamp (pushed from the XDP program) and min-RTT (adds in-kernel tracking of minimum RTT for each flow). Furthermore, I've added a simple JSON format as well as Kathie's "machine friendly" format (used by ppviz).

TODOs:
- Currently the program my report incorrect minimum-RTT if the tc program deletes the flow-information before the XDP program can calculate the RTT of a packet from that flow. Couple of options for fixes would be to only attempt to delete flow-information from the XDP program, or include the current min-RTT into the stored packet timestamp. 
- Update `README` and `TODO`

2021-05-04 11:34 UTC, tohojo requested changes
A few comments...

2021-05-04 11:34 UTC, tohojo commented on pping/pping.c
> +	20 // Length of string containing timestamp "HH:MM:SS"
No it isn't? ;)

("HH:MM:SS" is only 9 bytes long include null-byte)... Also, you can use sizeof() on a string constant, so you don't really need the define...

2021-05-04 11:34 UTC, tohojo commented on pping/pping.c
> +	strftime(timestr, TIME_STR_LEN, "%H:%M:%S", localtime(&time));
Full-second granularity is too long here (you'll get several data points for each second). Let's at least go down to ms accuracy (so "HH:MM:SS.ms")...

2021-05-04 11:34 UTC, tohojo commented on pping/pping_kern.c
> +	// Update flow's min-RTT, may have concurrency issues
May have? :)

2021-05-04 11:34 UTC, tohojo commented on pping/pping_kern.c
> +	event.min_rtt = f_state ? f_state->min_rtt : event.rtt;
Under what circumstances can this fail while the timestamp lookup above succeeds? And if it does, is outputing an event really the right thing to do?

2021-05-04 11:34 UTC, tohojo commented on pping/pping.c
> +	{ "json",             no_argument,       NULL, 'j' }, // Output in JSON format
How about making this a `--format` (`-F`?) argument instead? So you can do use `--format json` - makes it easier to add more formats without blowing through a lot of flags (that the user also has to remember).

2021-05-04 11:34 UTC, tohojo commented on pping/pping.c
> +	       ntohs(e->flow.saddr.port), daddr, ntohs(e->flow.daddr.port));
I am mildly horrified at this way of writing JSON ;)
But I don't *really* see any good reason why it won't do, at least for now...

2021-05-04 11:34 UTC, tohojo commented on pping/pping.c
> +	{ "machine-friendly", no_argument,       NULL, 'm' }, // Ouput in Kathie's "machine friendly" format
And then this could just be adding another possible argument to `--format`. Maybe even call it `ppviz` instead of "machine friendly"?

2021-05-04 18:28 UTC, simosund commented on pping/pping.c
> +	20 // Length of string containing timestamp "HH:MM:SS"
Yhea, originally used the format string "YYYY-MM-DD HH:MM:SS" (which is 20 characters including the null-byte) but thought it became a bit long. So did the somewhat unusual misstake of updating the documentation but not the code =). As you say though, probably much better to just have the format string and use `sizeof` on that to avoid these types of problems alltogether.

2021-05-04 18:29 UTC, simosund commented on pping/pping.c
> +	strftime(timestr, TIME_STR_LEN, "%H:%M:%S", localtime(&time));
Agree, but I suspect that just as Kathie I got a bit lazy when strftime didn't support anything lower by itself.

2021-05-04 18:36 UTC, simosund commented on pping/pping_kern.c
> +	// Update flow's min-RTT, may have concurrency issues
Well, can in theory of course end up with the situation where multiple packets for the flow is discovered to have the lowest RTT concurrently, and basically get a lost update. So similar problems as most of the other code that operates on these non-per-CPU maps, but got a bit tired of commenting about it as my tc program is mainly comments about possible concurrency issues at this point.

From my understanding from some previous discussions however these types of concurrency issues aren't too likely in reality as packets from the same flow are generally processed on the same core.

2021-05-04 18:42 UTC, simosund commented on pping/pping_kern.c
> +	event.min_rtt = f_state ? f_state->min_rtt : event.rtt;
The timestamp lookup of course has to succeed, but the flow-state lookup (which keeps the per-flow minimum RTT) doesn't have to. That flow information can potentially be deleted by the tc program if it detects that the flow is about to close before the XDP program has had time to get a response and compute an RTT. 

So this is basically what I refered to as the issue where the wrong minimum-RTT may be reported (mainly a possibility for the final RTT calculation for the flow). Have some changes in the works for this, which includes a bit less aggressive deletion of flow information and not outputting the RTT in case no relevant flow information can be found.

2021-05-04 18:43 UTC, simosund commented on pping/pping.c
> +	{ "json",             no_argument,       NULL, 'j' }, // Output in JSON format
Seems like a good idea. Don't currently plan on adding a whole lot of additional formats, but can never know what the future has in store.

2021-05-04 18:48 UTC, simosund commented on pping/pping.c
> +	       ntohs(e->flow.saddr.port), daddr, ntohs(e->flow.daddr.port));
Can understand that, but for the relativly simple JSON format I use I thought it was sufficent. If we start using a more nested JSON structure or similar I guess it makes sense to move towards some kinda of JSON-builder, although not sure how you feel about additional depedencies for the bpf-examples.

2021-05-04 18:50 UTC, simosund commented on pping/pping.c
> +	{ "machine-friendly", no_argument,       NULL, 'm' }, // Ouput in Kathie's "machine friendly" format
Sure. Simply kept the name that Kathie used for it, but it's primary use case is pretty much `ppviz`, so that's probably more descriptive/telling.

2021-05-05 04:50 UTC, tohojo commented on pping/pping_kern.c
> +	// Update flow's min-RTT, may have concurrency issues
Yup, totally agree that leaving comments about concurrency issues sprinkled throughout code is just tedious, especially if they're vague ones like this one. Which was kinda the point of my comment ;)

Ideally this is something that will be handled at the design level. Which would in this case mean documenting the assumptions in one place, and they either referring to that in the code, or just leaving out comments like this one entirely :)

2021-05-05 04:53 UTC, tohojo commented on pping/pping_kern.c
> +	event.min_rtt = f_state ? f_state->min_rtt : event.rtt;
Right, but my point was more that if the flow state is not present (because it has been garbage-collected), is it really appropriate to output a data point? The even says it contains the "min rtt" of the flow, so if we don't know what that is, shouldn't we either say so (min_rtt = 0), or abort entirely (just skip the event)?

2021-05-05 07:12 UTC, simosund commented on pping/pping_kern.c
> +	event.min_rtt = f_state ? f_state->min_rtt : event.rtt;
Yhea, my plan for now is to skip the event entierly in those instances.

2021-05-05 09:46 UTC, tohojo commented on pping/pping_kern.c
> +	event.min_rtt = f_state ? f_state->min_rtt : event.rtt;
OK, SGTM :)

2021-05-05 11:07 UTC, abrunstrom commented on pping/pping.c
> +	strftime(timestr, TIME_STR_LEN, "%H:%M:%S", localtime(&time));
Thinking also about more local use case, like latency between VMs, even ms granularity may perhaps be too course grained.

2021-05-05 11:14 UTC, abrunstrom commented on pping/pping_kern.c
> +	// Update flow's min-RTT, may have concurrency issues
Losing a minRTT update does not seem very critical. When sampling, the minRTT is anyway an estimate and if you had sampled a different packet you would anyway have missed it.

2021-05-05 11:44 UTC, simosund commented on pping/pping.c
> +	strftime(timestr, TIME_STR_LEN, "%H:%M:%S", localtime(&time));
> Thinking also about more local use case, like latency between VMs, even ms granularity may perhaps be too course grained.

Well, we're talking about the timestamp here and not the RTT (which is printed in ms with 6 decimals, so nanosecond resolution), so not sure if I see why it matters if it's local or not (in some sense I guess the timestamp when we recieve the packet the RTT is calculated for is always local). For the JSON and "machine friendly"/ppviz format the timestamp is printed with nanosecond resolution, but for the "standard" console output I'm not sure that's of much use to the user. If events are printed out so fast they can't even be differentiated with ms-resolution the "standard" format is probably not what you should be using to begin with.

2021-05-05 14:34 UTC, abrunstrom commented on pping/pping.c
> +	strftime(timestr, TIME_STR_LEN, "%H:%M:%S", localtime(&time));
My thought with local was that then we may have very short RTTs with a possibility and need for a much higher sampling rate, so having a fine granular timestamp may be needed to separate the samples. But if we have it in the timestamp for the JSON and ppviz format and that is what we will use for the actual measurements and this format is only for live visual inspection I agree it is not useful. But if you want to make a short test run, pipe the output to a file and then make some simple post processing or visually inspect the result it may still be good to make sure all the timestamps are unique?

2021-05-06 12:35 UTC, simosund commented on pping/pping.c
> +	strftime(timestr, TIME_STR_LEN, "%H:%M:%S", localtime(&time));
Hmm, guess that's sort of a valid point. Have added the full nano-second resolution of the timestamp in the default output mode now as well. Initially wanted to try and prevent the output from getting so wide, but as I don't do the adaptive us/ns unit selection and rounding of RTTs that Kathie does my output is already a fair bit wider anyways. 

Even with no sampling at all however you're still not very likely to get output at a higher rate than 1000 Hz within a single flow due to TCP timestamps only being updated at 1000Hz.

2021-05-06 12:43 UTC, abrunstrom commented on pping/pping.c
> +	strftime(timestr, TIME_STR_LEN, "%H:%M:%S", localtime(&time));
That is true, i did not think about the TCP timestamp update rate. Maybe with another protocol... Pick what you feel is best.

2021-05-06 13:27 UTC, tohojo commented
abrunstrom ***@***.***> writes:

> @abrunstrom commented on this pull request.
>
>
>
>>  
>  	format_ip_address(e->flow.ipv, &e->flow.saddr.ip, saddr, sizeof(saddr));
>  	format_ip_address(e->flow.ipv, &e->flow.daddr.ip, daddr, sizeof(daddr));
> +	strftime(timestr, TIME_STR_LEN, "%H:%M:%S", localtime(&time));
>
> That is true, i did not think about the TCP timestamp update rate.
> Maybe with another protocol... Pick what you feel is best.

Just because a flow doesn't *emit* new timestamps closer together than
1ms, doesn't guarantee that they don't *arrive* within the same ms,
though. Say if two consecutive timestamps are caught up in the same
queue and then released together. Middlebox shenanigans can also play
into this (ACK thinning, for one).

2021-05-06 13:48 UTC, simosund commented
> Just because a flow doesn't *emit* new timestamps closer together than
1ms, doesn't guarantee that they don't *arrive* within the same ms,
though. Say if two consecutive timestamps are caught up in the same
queue and then released together. Middlebox shenanigans can also play
into this (ACK thinning, for one).

Good point. Anyways, as of commit [f6cf8ed](https://github.com/xdp-project/bpf-examples/pull/16/commits/f6cf8edd96243f1f5a6d44e6ce66eaae2ac73a3a) I now output timestamps in all formats (including the standard one) with nanosecond resolution. The accuracy is probably a bit lower though, partly because I don't actually take the timestamp before I've parsed the packet, and partly because having to convert between `CLOCK_MONOTONIC` and `CLOCK_REALTIME`)

2021-05-07 15:06 UTC, tohojo commented
Simon Sundberg ***@***.***> writes:

> Hi @tohojo, just realized that in its current form you can only run pping on a single interface, as if you try to run it on another it will fail pinning the tc program (as it will try to pin it to the same place as the tc program for the other interface). 
>
> Thinking we could just add some random suffix to the pinned location (so instead of pinning to `/sys/fs/bpf/pping/classifier` it pins it to `sys/fs/bpf/pping/classifier_<random_suffix>`) that makes it rare enough that they "should" never crash. Another option I guess would be to add the interface name as a suffix, but that might not work if you want to attach them inside virtual environments (could for example then have multiple veth0 interfaces). 
>
> Or do you have any other ideas on how to best solve it?

Why is the pinning staying around? You can unlink the pinned file as
soon as you've loaded the program with TC, no? in which case the race
window is quite small, so you could just retry if you hit it on the
second run...

2021-05-10 09:27 UTC, simosund commented
> Why is the pinning staying around? You can unlink the pinned file as
soon as you've loaded the program with TC, no?

Hmm, for some reason I just assumed that it wouldn't work. But of course that works and is overall a much nicer solution than having a bunch of pinned programs staying around with different names.

2021-05-10 11:06 UTC, tohojo requested changes
Looks mostly good now, but may be worth it to think a little more about extensibility of the JSON format ahead of time... :)

2021-05-10 11:06 UTC, tohojo commented on pping/pping.c
> +	       "\"dest_ip\":\"%s\", \"dest_port\":%d, \"protocol\":\"%s\", "
Including the protocol is a good idea. It may be worth thinking about what the format is supposed to be if it's not TCP in more detail, though. For instance, ICMP has no port numbers; so what will src_port and dest_port contain if it's an ICMP flow? Will they be omitted? or null? or something else?

2021-05-10 11:06 UTC, tohojo commented on pping/pping.c
> +		return "ICMPv6";
No love for UDP? ;)

2021-05-10 11:06 UTC, tohojo commented on pping/pping.c
>  	format_ip_address(e->flow.ipv, &e->flow.daddr.ip, daddr, sizeof(daddr));
It just occurred to me that most other "print" type functions (e.g., sprintf) has the target buffer as the first argument; so this looks a little odd...

2021-05-10 16:08 UTC, simosund commented on pping/pping.c
>  	format_ip_address(e->flow.ipv, &e->flow.daddr.ip, daddr, sizeof(daddr));
Well, guess I could just change order to: (buffer, buffer-size, ip-version, ip-address) then to follow convention a bit better.

2021-05-10 16:41 UTC, tohojo commented on pping/pping.c
> +		return err;
Ah, right, there's a separate bit of cleanup in the main function. It would be better to put that into this function; the way it is now, you have to keep the state of the entire program in your head to know that things are being cleaned up correctly; making each function clean up properly after itself makes it way easier to reason about the behaviour...

2021-05-27 17:27 UTC, simosund commented
Hi @tohojo, I've now tried to refactor the code to accommodate some of your requests, and also moved to using the json-writer from iproute. For now I've simply copied the files directly to the `pping` folder, but guessing they're maybe supposed to go into a `lib/util` folder instead?

Have limited experience with larger projects in general, and the Makefiles for this project are a bit more complicated than the trivial ones I've had to work with during my education. So its not clear to me exactly how additional dependencies are supposed to be added here.

2021-06-01 15:24 UTC, tohojo requested changes
Better, but a few more comments.

I also pushed an update to the libbpf submodule so you should be able to switch to using the libbpf TC API methods instead of shelling out now :)

2021-06-01 15:24 UTC, tohojo commented on pping/pping.c
> +cleanup:
Instead of having one label and multiple conditionals in the cleanup path, try using different labels for each error. This makes the code more readable and also forces you to do the cleanup in the opposite order as when you were setting things up, which is good practice. Have a look at the error path in __dev_map_alloc_node() as an example:

https://elixir.bootlin.com/linux/latest/source/kernel/bpf/devmap.c#L583

2021-06-01 15:24 UTC, tohojo commented on pping/Makefile
> +LIB_OBJS += json_writer.c
This is not meant to be set at all from the program Makefiles. I pushed some updates to common.mk that adds the lib/util directory, so you should be able to rebase and then just drop the json_writer files into there (and update util.mk of course).

2021-06-01 16:15 UTC, simosund commented on pping/pping.c
> +cleanup:
Hmm, seems reasonable. Got into my head that `goto` is the root of all evil that will instantly lead to spaghetti code and therefore tend to avoid it. But avoiding it definitly leads to some rather clumsy conditionals at times.

2021-06-01 16:19 UTC, simosund commented on pping/Makefile
> +LIB_OBJS += json_writer.c
Thanks, was guessing it was supposed to go into `lib/util`, but as there was no previous example to go by there I felt a bit unsure and figured it would be easier to just ask you =).

2021-06-01 21:01 UTC, tohojo commented on pping/pping.c
> +cleanup:
Oh you mean like this? https://xkcd.com/292/

When used wrong, gotos can indeed lead to spaghetti code, but used correctly they can improve readability. In particular the "labels for error handling" pattern is extremely common in kernel code and it does help I think.

For another example that's a bit more questionable (but still IMO arguably acceptable due to its very specialised use case), feast your eyes upon this efficient memcpy implementation from the Cilium code base: https://github.com/cilium/cilium/blob/master/bpf/include/bpf/builtins.h#L163

2021-06-01 21:01 UTC, tohojo commented on pping/Makefile
> +LIB_OBJS += json_writer.c
Yup, good thinking :D

2021-06-02 07:42 UTC, simosund commented on pping/pping.c
> +cleanup:
> Oh you mean like this? https://xkcd.com/292/

Haha, yhea pretty much. Will constantly be looking over my shoulder to check for velociraptors now =).

2021-06-02 10:04 UTC, tohojo commented on pping/pping.c
> +cleanup:
Don't worry, they are extinct in most of the world - just stay away from secluded tropical islands owned by crazy billionaires and you should be fine ;)

2021-06-02 11:22 UTC, simosund commented on pping/pping.c
> +cleanup:
Hmm, not sure if my brain is just a bit slow today, but have to admit I'm struggeling somewhat to not get eaten by velociraptors right now when trying to apply this "goto err"-pattern. My problem is that the code for unpinning the tc program should run both on success and errors (as long as the tc program has first been pinned). Furthermore, unpinning the tc-program may also fail (and should in that case also detach the tc and xdp programs if they've previously been attached). 

So when I try to follow this structure I land in something like this (pseudo-code):

```
int load_attach_progs()
{
       // Some code of loading the obj-file

        err = pin_tc_prog();
        if (err)
                return err;
        
        err = attach_tc_prog();
        if (err)
                goto err_tc;
        
        err = attach_xdp_prog()
               goto err_xdp;

        err = unpin_tc_prog()
        if (err)
               goto unpin_err;
        return 0;

unpin_err:
        detach_xdp_prog()
xdp_err:
        detach_tc_prog();
tc_err:
        unpin_tc_prog();  // Duplicate code, may run unpin_tc_prog() twice
        return err;
}
```

This is not particularly pretty as I then have to duplicate the code for unpinning the tc program (once in the normal path, and once in the error-handling path), and if the initial unpinning of the tc-program fails (unpin_err), then it will attempt to unpin it again (which I would expect would just fail again, and print an additional error message about the same issue).

I could of course use an additional jump in the normal path to avoid duplicating the unpin_tc_prog() code, something similar to this:
```
int load_attach_progs()
{
       // Some code of loading the obj-file

        err = pin_tc_prog();
        if (err)
                return err;
        
        err = attach_tc_prog();
        if (err)
                goto err_tc;
        
        err = attach_xdp_prog()
               goto err_xdp;

        goto tc_err; // Not an acutal error, just want to unpin the tc prog

unpin_err:
        detach_xdp_prog()
xdp_err:
        detach_tc_prog();
tc_err:
        err = unpin_tc_prog();
        if (err)
                goto unpin_err; // Causes infinite loop if unpin_tc_prog() fails, will incorrectly try and detach xdp and tc programs if tc_attach_prog() failed.
        return err;
}
```
But this is obviously very broken. Could fix that by making the jump to unpin_err conditional, but at that point I'm back to having conditions in my cleanup code again as well as having jumps, making the whole thing a more confusing version of the original code IMO. Ex.

```
int load_attach_progs()
{
       // Some code of loading the obj-file

        bool do_back_jmp = false;

        err = pin_tc_prog();
        if (err)
                return err;
        
        err = attach_tc_prog();
        if (err)
                goto err_tc;
        
        err = attach_xdp_prog()
               goto err_xdp;

        do_back_jmp = true;
        goto tc_err; // Not an acutal error, just want to unpin the tc prog

unpin_err:
        detach_xdp_prog()
        do_back_jmp = false;
xdp_err:
        detach_tc_prog();
tc_err:
        err = unpin_tc_prog();
        if (err && do_back_jmp)
                goto unpin_err;
        return err;
}
```

2021-06-02 14:46 UTC, tohojo commented on pping/pping.c
> +cleanup:
So when error handling ends up being too gnarly that is usually a good sign that the code needs refactoring :)

In this case, logically pinning is part of TC attach. Also, if unpinning fails after attaching the TC prog there is no way to avoid ending up in an inconsistent state (since no matter what you do you'll end up with the program still being pinned). So arguably it's enough to just warn and continue - so how about:

```C
int attach_tc_prog()
{
        err = pin_tc_prog();
        if (err)
                return err;

        err = __attach_tc_prog(); // do the actual attach

        /* we need to unpin regardless of whether attach succeeded, and
         * we can't really do anything about it if unpinning fails, so just warn
         * and continue if it does fail.
         */
        unpin_err = unpin_tc_prog();
        if (unpin_err)
             warning("couldn't unpin TC prog: %s", strerror(unpin_err));
        return err;
}

int load_attach_progs()
{
       // Some code of loading the obj-file

        err = attach_tc_prog();
        if (err)
                return err;
        
        err = attach_xdp_prog();
        if (err)
               goto err_xdp;
        return 0;

err_xdp:
        detach_tc_prog();
        return err;
}
```

This has the added benefit of making it really straight-forward to replace the code with the libbpf TC API later :)

2021-06-02 19:56 UTC, simosund commented on pping/pping.c
> +cleanup:
Should have been able to figure that out myself... Anyways, thanks for the help!

2021-06-03 15:12 UTC, simosund commented
Hi again @tohojo. Hopefully the cleanup code looks a bit better now.

While I don't think you need to do another review yet (although if you want to I of course welcome the feedback), I am wondering what you think of my overall approach to implementing start/end of flow messages.

I didn't want to add a bunch of additional fields to the existing `rtt_event` struct (which I pass to userspace through the perf-buffer when an RTT is computed) that wouldn't be used for the RTT-messages. Likewise many of the existing fields in the RTT event wouldn't be used for the start/end of flow messages.

Therefore, I've instead added a new type of `flow_event` struct. To be able to send both of these through the same perf-buffer I added a `event_type` member to the beginning of them (which is only 8 bytes for the sake of struct alignment, for now a single bit would be sufficent otherwise) that can be used to differentiate between the two when receiving them. I've also reorderd the fields a bit so that all the fields that both event types have in common come first (and in the same order) to make the use of the common part a bit easier to use.

But now I've started to wonder if perhaps it would be better to just utilize a single event struct, and then use a union to allow for different interpretation of the (non-common) data fields. The drawback of this is that such a struct would be unecessarily large  for the "flow events" (which at least so far are a fair bit smaller than the RTT events due to not having so many 8-byte members). But thinking it would be somewhat easier to maintain (don't need to keep two different structs in sync), and for the XDP program it would be possible to reuse its existing rtt_event for another flow_event to save a little bit of stack-space and computation.

As for my current implementation, I'm also not a huge fan of how I on the BPF side directly access and fill in different values of the `flow_event` struct from different functions in a way where they all sort of have to be aware of eachtoher for it to work properly. Guess I could maybe package the `event` and `reason` memebers into their own struct to get a bit better logical seperation for `parse_packet_identifier()` at least.

But to summarize, what do you think of the overall approach? Is it reasonable, or should I switch to the "single struct with union" approach I mentioned, or something different entirely?

2021-06-07 14:28 UTC, tohojo commented
How about multiple structs with a union? :)

I.e., keep the two structs and define a union like:

```C
struct flow_event;
struct rtt_event;

union pping_events {
  __u64 event_type;
  struct flow_event;
  struct rtt_event;
};
```

Then code reading events can do something like:

```C
union pping_events *evt = get_event();
if (evt->event_type == EVENT_TYPE_FLOW) 
  process_flow_event(&evt->flow_event);
else if (evt->event_type == EVENT_TYPE_RTT)
  process_rtt_event(&evt->rtt_event);
```

Another thing to consider when designing a protocol like this (because at this point, you've ventured into protocol design; congratulations! ;)), is whether it needs to be extensible. I.e., with a design like this, the reader has to know the entire definition to be able to do anything sensible with the data; and if any of the structs ever get extended, the reader won't know which version is being used. For a perf buffer event, the reader can get the event size from there and infer the version of the struct; but if, say, you ever decide to stick two events into the same buffer, the length also needs to be encoded along with the type (AKA TLV encoding).

This is not a problem if BPF code and userspace code are always upgraded together; but it's worth thinking about anyway, because that might change (say if there's a long-running program loaded into the kernel where various userspace implementations need to read the data out).

2021-06-07 16:33 UTC, simosund commented
> How about multiple structs with a union? :)

Hmm, I guess that's slightly prettier than my current solution. As both the flow-events and rtt-events have a timestamp + flow-tuple, I'll probably have some common part for printing those out which will pretend that it is ex. a rtt-event regardless of if it is an rtt-event or flow-event.

> Another thing to consider when designing a protocol like this (because at this point, you've ventured into protocol design; congratulations! ;)), is whether it needs to be extensible. 

Why can nothing ever be simple? =) Guess we can discuss this a bit during the meeting tomorrow.

2021-06-11 13:11 UTC, simosund commented
Hi @tohojo, 
I've now tried switching to using libbpf to attach the tc program. I'm not entirely sure I've understood the API correctly though, so would be great if you could have a look at that (commit [9a4fa42](https://github.com/xdp-project/bpf-examples/pull/16/commits/9a4fa4288713258f206ebb02639bd5db0fb2b64a)). 

The API-description in the [commit](https://github.com/libbpf/libbpf/commit/d71ff87a2dd7b92787719aab233767e9c74fbd48) that added the TC-BPF API mentioned that you could check if a qdisc had any filters attached before deleting it, but couldn't figure out how to do that correctly. So right now the cleanup isn't 100% working as it still leaves the clsact qdisc. As I mentioned in the commit message I guess I could just use the previous solution of simply deleting the qdisc regardless if it's used by anything else or not, but figured that's probably a bad idea in case it actually is used by something else.

2021-06-12 18:36 UTC, tohojo commented
Hmm, the tc code went through quite a few revisions, so not sure what happened to the wildcard query; maybe it got dropped somewhere on the way? @kkdwivedi should know...

2021-06-12 19:19 UTC, kkdwivedi commented
Yeah, multi query/wildcard query was dropped, but looks I forgot to remove its description from the commit message (ouch).

So that example is pretty much broken and doesn't work. Right now you should just leave the clsact qdisc as is, since even what that example suggests (probing for zero filters) is inherently racy, as some else could install a filter between check and deletion.

2021-06-12 19:24 UTC, kkdwivedi commented on pping/pping.c
> +	err = bpf_tc_hook_create(&hook);
You would want to handle EEXIST here. This can happen when there is clsact, or the ingress qdisc installed on the interface. Also maybe avoid hook_destroy (or atleast only do it when you created the qdisc).

2021-06-14 16:43 UTC, simosund commented
> Yeah, multi query/wildcard query was dropped, but looks I forgot to remove its description from the commit message (ouch).

> So that example is pretty much broken and doesn't work. Right now you should just leave the clsact qdisc as is, since even what that example suggests (probing for zero filters) is inherently racy, as some else could install a filter between check and deletion.

Thanks for clearing that up! In that case I'll simply drop the `del_tc_hook_if_empty()` function for now and let the clsact qdisc hang around (guess it shouldn't cause much harm sitting there unused?).

2021-06-14 17:15 UTC, simosund commented on pping/pping.c
> +	err = bpf_tc_hook_create(&hook);
Sounds like a good idea. However, I've been unable to get `bpf_tc_hook_create()` to actually return `EEXIST`. If the clsact qdisc already exists it still seems to return 0 and chug along nicely (and if it doesn't exist, it of course creates it and returns 0). If an ingress qdisc is installed on the interface it instead seems to return -`EINVAL`.

2021-06-14 17:19 UTC, kkdwivedi commented on pping/pping.c
> +	err = bpf_tc_hook_create(&hook);
I guess that would be because of missing this... https://lore.kernel.org/bpf/20210612023502.1283837-1-memxor@gmail.com/T/#m7174e4ca28fe08d6ffd204696f9968085f96cdf8

2021-06-14 17:21 UTC, kkdwivedi commented on pping/pping.c
> +	err = bpf_tc_hook_create(&hook);
So I guess you can still handle it, since it would break when this is applied.

2021-06-14 17:58 UTC, simosund commented on pping/pping.c
> +	err = bpf_tc_hook_create(&hook);
Ah, ok. Will do.

2021-06-21 11:04 UTC, tohojo commented
So this PR is turning into a grab-back of random improvements, not just output improvements. Could you please restructure it so that it actually does what it says on the tin (i.e., contains only the output stuff)? Then we can merge it and you can do the other fixes in a separate PR.

Also, please squash all the small "fixes" commits so that the commit messages are coherent and explain the changes; as a totally random sample, commit 537c9c5b9cd5d93f97384f69b8798206453de9e1 is a candidate for squashing, for instance...

2021-06-21 17:40 UTC, simosund commented
> So this PR is turning into a grab-back of random improvements, not just output improvements. Could you please restructure it so that it actually does what it says on the tin (i.e., contains only the output stuff)? Then we can merge it and you can do the other fixes in a separate PR.

You are right about that, think most of the output related stuff have been finished at this point, but have just continued pushing other fixes here as well after that (and also a bit in the middle I guess...). As we discussed in the meeting, I guess we can add a "miscellaneous fixes" PR and move those unrelated fixes there.

So guess the main thing to break out from this PR is using libbpf's tc-attach API together with my most recent fix checking the ACK-flag before parsing TSecr. The refactoring of the cleanup code is also not really related to the output, although it does address one of your requested changes in this PR. I can still try to break that out (and probably squash those two refactoring commits together) and hopefully not break anything too badly in the process.

Adding flow events and packet/byte counts I think is related to improving the output (even if it of course entails some other changes in order to collect the data needed for that improved output).

I guess the commit that adds information about concurrency issues to the README (and removes concurrency comments from the code) isn't exactly related to the output. However as many updates to the README also contains various minor spelling fixes, updates to the concurrency section etc. I think it might be tricky to break that out at this point. 

> Also, please squash all the small "fixes" commits so that the commit messages are coherent and explain the changes; as a totally random sample, commit 537c9c5 is a candidate for squashing, for instance...

I guess that goes for small fixes that are related to, and can relativly easily be included in, previous commits as parts of a larger change. For example, my latest commit about avoiding TSecr if the ACK flag is a small fix, but isn't set isn't really related to anything else in any remotely recent commit (and should as previously stated not even be in this PR).

2021-06-22 16:57 UTC, simosund commented
Hi @tohojo, I have rewritten the history a bit now so it should hopefully be a bit easier to follow, and no longer include a bunch of stuff not related to improving the output (or at least reducing it to a much smaller degree). So please have a look at it and let me know if there's anything else you would like me to change before merging.

2021-06-23 13:32 UTC, simosund commented
With the recent force-push I just added some fixups that updated the TODO for the "Add timestamp..." and "Add machine friendly format" commits.

2021-06-24 12:28 UTC, merged