Created DHCP relay user and xdp program to insert DHCP option 82
xdp-project/bpf-examples pull request #22
Opened 2021-06-10 23:04 UTC by sachints123

Initial working version of DHCP relay using XDP is created. Currently, this code has
user program and a xdp ebpf program. User program takes network interface and dhcp relay server IP
as inputs and store it in a map. XDP program filters the incoming DHCP requests and inserts
option 82 in the DHCP request packets and overwrites the destination IP to that of DHCP relay server IP.
An optional argument for user program is also provided to unload the xdp program.
README file provides to instructions to build and load the xdp program.

Signed-off-by: sachints123 <sachin.tiptur.satyanarayana.gupta@hof-university.de>

2021-06-11 11:06 UTC, tohojo requested changes
A bunch of comments, most of which are minor-ish style issues. In particular, please fix up the code style throughout. There are tools that can help you with that (like clang-format). You can grab the .clang-format file from the Linux kernel source directory for the correct style...

Also, please remove the binary files from the commit (.dhcp_kern_xdp.c.swp and dhcp_user_xdp). I'd suggest adding a .gitignore for them instead.

For the commit message, please make the title short and descriptive (like "Add DHCP relay program") and reflow the commit message itself to be 80 characters wide. Also please use your full name instead of your github username in the signed-off-by line.

When updating the PR, just update the existing commit (with `git commit --amend` instead of creating new ones on top of this one. If you prefer to keep the history you can of course also create a new local branch and work on the changes, but the PR should stay as one commit...

2021-06-11 11:06 UTC, tohojo commented on dhcp-relay/dhcp-relay.h
> +	};
Indentation error

2021-06-12 21:18 UTC, sachints123 commented on dhcp-relay/README
> +sudo ./dhcp_user_xdp <netif> <dhcp relay IP> 1
Like instead of 1, shall i use on/off strings?  and should I handle using optargs?

2021-06-13 18:39 UTC, sachints123 commented on dhcp-relay/dhcp_kern_xdp.c
> +  	ether_type = parse_ethhdr_vlan(&nh, data_end, &eth, &vlans);
If there are no enough vlan tags then should we skip inserting option82?

2021-06-13 20:01 UTC, tohojo commented on dhcp-relay/dhcp_kern_xdp.c
> +  	ether_type = parse_ethhdr_vlan(&nh, data_end, &eth, &vlans);
Yeah, either skip processing, or go straight to XDP_ABORTED to drop the packet...

2021-06-14 22:24 UTC, tohojo requested changes
Much better! A few more smallish issues to fix, then I think we're good to go.

Also, you seem to have accidentally included a change to the libbpf submodule in your commit; please get rid of that. And while adding the .clang-format file is fine, it should be in a separate commit, and added to the top-level directory so we can use it everywhere :)

2021-06-14 22:24 UTC, tohojo commented on dhcp-relay/dhcp_kern_xdp.c
> +	(sizeof(struct ethhdr) + DHCP_UDP_OVERHEAD +                           \
Let's use `sizeof(struct iphdr) + sizeof(struct udphdr)` here instead of `DHCP_UDP_OVERHEAD`

2021-06-14 22:24 UTC, tohojo commented on dhcp-relay/dhcp_kern_xdp.c
> +	if (xdp_store_bytes(ctx, 0, buf, MAX_BYTES, 0))
Instead of this double-copy we should just extend __bpf_memcpy() to handle the size we need. Just pushed a change to extend it by another 8 bytes, which I think is enough, right? So just rebase and do this in one go with the full size...

2021-06-14 22:24 UTC, tohojo commented on dhcp-relay/dhcp_user_xdp.c
> +	printf("To unload program:\n dhcp_user_xdp -i eth0 -u\n");
Let's use argv[0] here as well instead of hard-coding the program name...

2021-06-14 22:24 UTC, tohojo commented on dhcp-relay/dhcp_user_xdp.c
> +			strncpy(dev, optarg, IF_NAMESIZE);
If `strncpy()` fails it'll leave the buffer without a terminating NULL byte, leading to subsequent overflows; so you need to do something like:
```C
strncpy(dev, optarg, IF_NAMESIZE-1)
dev[IF_NAMESIZE-1] = '\0';
```

2021-06-14 22:24 UTC, tohojo commented on dhcp-relay/dhcp_user_xdp.c
> +			}
Better handle invalid values as well here (and support 'native' as a no-op as well for good measure)

2021-06-14 22:24 UTC, tohojo commented on .gitignore
> +dhcp-relay/dhcp_user_xdp
Better to just create a separate .gitignore file in the dhcp-relay directory...

2021-06-21 10:08 UTC, tohojo requested changes
Git history looks fine now; found a few more minor issues in the code, please fix. Also, there's a second signed-off-by tag with your username in the commit message, just get rid of that and keep the one with your name on it :)

2021-06-21 10:08 UTC, tohojo commented on dhcp-relay/dhcp_kern_xdp.c
> +	oldip = *ip;
If you also store the byte offset here (`ip_offset = ip - data`), you can get back to the IP header after adjusting the packet size without re-parsing the packet (see comment below)

2021-06-21 10:08 UTC, tohojo commented on dhcp-relay/dhcp_kern_xdp.c
> +		return XDP_ABORTED;
This should just be `goto out`

2021-06-21 10:08 UTC, tohojo commented on dhcp-relay/dhcp_kern_xdp.c
> +		goto out;
here you've already extended the packet, so needs to return XDP_ABORTED

2021-06-21 10:08 UTC, tohojo commented on dhcp-relay/dhcp_kern_xdp.c
> +					goto out;
And here as well (`XDP_ABORTED`)

2021-06-21 10:08 UTC, tohojo commented on dhcp-relay/dhcp_kern_xdp.c
> +		return XDP_ABORTED;
Instead of re-parsing the packet, you can just use the offset (if you store it as suggested above):
```C
ip = data + ip_offset;
if (ip + 1 > data_end)
	return XDP_ABORTED;
```

The range check is needed to appease the verifier, but won't actually ever fail...

2021-06-21 10:08 UTC, tohojo commented on dhcp-relay/dhcp_user_xdp.c
> +			} else {
I think it's better to fail on an invalid value; so rather `else if (strcmp(optarg, "drv") != 0) { fprintf(stderr, "Invalid mode: %s\n", optarg); return -EINVAL; }`

2021-06-21 10:08 UTC, tohojo commented on dhcp-relay/dhcp_user_xdp.c
> +*/
Indentation error; also s/realy/real/ ?

2021-06-21 20:57 UTC, tohojo approved these changes
The .swp file snuck back in and the commit author name doesn't match the sign-off line making the bot unhappy. I'll fix up both of those while applying, the rest looks good. Nice work!

I'd suggest you amend your local git config to avoid those issues in the future. Something like:
```
git config --global user.name 'Sachin Tiptur'
git config --global core.excludesfile ~/.gitexclude
echo '*.swp' >> ~/.gitexclude
```

2021-06-21 20:58 UTC, tohojo commented
Merged as 0c8df86a5eeb8dc17088a281ce082651375d8f32

2021-06-21 20:58 UTC, closed without merging