PPing - Improve map cleanup
xdp-project/bpf-examples pull request #34
Opened 2021-12-10 16:17 UTC by simosund

These commits moves the cleanup logic for stale entires from userspace to a BPF iter program. So instead of userspace periodically looping through the maps clearing out old entries, it only triggers the BPF programs periodically, and the BPF program iterates through all the entries removing  those which are considered old.

Also adds some slightly more complex logic for when an entry can be removed, for example ICMP flows and unopened TCP flows can be cleared faster than an open TCP flow, and timestamp entries with low RTTs can be cleared much faster than the static 10s limit.

All these commits were created with the changes from [PR#23](https://github.com/xdp-project/bpf-examples/pull/23) in mind, more specifically with those that are now in [PR#32](https://github.com/xdp-project/bpf-examples/pull/32). While the first two commits could potentially work without PR#32, the commit with more aggressive cleanup is based on the existance of ex. ICMP flows and "unopened" flows, and therefore makes little sense to merge before PR#32. I will therefore leave this as a draft for now.

2022-02-10 17:50 UTC, simosund commented
Now that [PR#32](https://github.com/xdp-project/bpf-examples/pull/32) has been merged I will rebase this and probably do some minor touchups. Once I'm done with that I will remove the draf-status.

2022-02-17 14:40 UTC, simosund commented
I have now rebased this PR on the current master, done a little cleanup based on comments from previous PRs, and also changed the a couple of things I thought was a bit clumsy in my initial PR.

For reference, the state of this PR before these changes can be found on [this branch](https://github.com/simosund/bpf-examples/tree/pping_better_map_cleaning_backup_20220216) (which has not been rebased). The first major change from this old version is that I used to send the debug information from the BPF iter programs to the userspace process through an additional map that I would read right after I had triggered the BPF iter programs that updated them in userspace. I now instead treat the debug information as a new type and simply push them through the perf-buffer like all other evens, which requires much fewer changes in the userspace code.

The second major change from the old version is related to adding RTT-based timeouts to the timestamp entries. In the old version I added the current RTT to every timestamp entry to avoid doing a flow lookup for each timestamp entry in the BPF iter program. However, this adds additional information stored for each timestamp entry, and as the normal ePPing program does a flow lookup for every (valid) packet anyways, the overhead of doing a lookup for a few thousand entries every cleanup period (by default 1 second) is likely negligible. So I changed my mind on this and decided to leave the timestamp entries unchanged and simply do the lookup in the BPF-iter program instead.

2022-03-07 18:07 UTC, tohojo requested changes
Only a few nits on this one :)

2022-03-07 18:07 UTC, tohojo commented on pping/pping.c
> +		return ERR_PTR(linfo.map.map_fd);
You're making a lot of assumptions about the inner workings of libbpf_get_error() here (and below). This is bound to break (its semantics are already changing upstream), so I don't think this is a good idea (and it also happens to be a bit ugly).

I'd suggest you change this function to return an int error message, and add a `struct bpf_link **link` parameter to put the output in.

2022-03-07 18:07 UTC, tohojo commented on pping/TODO.md
> +## RTT-based cleanup of timestamp entries
While you're documenting issues, I think it would be worth mentioning (and keeping in mind) that the map iteration may end up missing entries on delete (due to the way the hash map traversal is implemented). Specifically, if you have a hash collision (i.e., more than one item in a bucket), and you delete one of the entries there, you'll end up skipping the other entry in the same bucket.

I don't think this is a huge deal (you'll just catch it in the next cleanup), but since you're documenting all the limitations I think it would be worth mentioning :)

2022-03-08 10:15 UTC, simosund commented on pping/pping.c
> +		return ERR_PTR(linfo.map.map_fd);
Have changed as you suggested to simply returning an int error message and instead pass out the link reference through a parameter. Still use `libbpf_get_error()` to catch errors for functions that return pointers (as I assume that's what the function is for), but no longer attempt to return error codes masked as pointers myself.

While fixing I also noticed another bug which I fixed. The `if (linfo.map.map_fd < 0)` check would always fail as `linfo.map.map_fd` is a __u32 and thus cannot be negative. Therefore I now first save the result from `bpf_object__find_map_fd_by_name()` in an int which I use for the error check, before assigning it `linfo`. Alternatively I guess I could also just cast `linfo.map.map_fd` for the check, but then I have to assume that ints are always 32 bits.

2022-03-08 10:16 UTC, simosund commented on pping/TODO.md
> +## RTT-based cleanup of timestamp entries
Good point, was not aware of that. Have added it to the list.

2022-03-08 13:40 UTC, tohojo requested changes
Better, but there's a bug; and spotted another issue while looking at the code again...

2022-03-08 18:52 UTC, simosund commented on pping/pping.c
> +	err = libbpf_get_error(link);
Sounds like a good idea. Have changed this now.

2022-03-08 18:52 UTC, simosund commented on pping/pping.c
> +		return err;
That is indeed the case. I haven't really fully grasped what these links even are and guess I pretty much just assumed they would automatically be destroyed and cleaned up on program exit together with all the other bpf objects (programs, maps etc. that aren't pinned).

To fix this I will need to restructure the code a bit to expose the links outside of this function so that I can access them later.

However, while thinking about this I just noticed what I think should be a much bigger error in the same function (`setup_periodical_map_cleaning()`). I allocate the arguments (including these links) which will be used in a different thread on the stack... So the arguments my cleanup function (`periodic_map_cleanup()`) use in a separate thread may be overwritten by whatever other functions I call in main later. Either I'm just not thinking straight right now, or it's a miracle that this hasn't caused all sorts of funky errors already.

I should probably also handle my cleanup thread on shutdown, so I don't just pull out these links underneath it and hope it never has time to notice before the entire program terminates. So will go ahead and add a separate commit at the beginning of this PR that address these issues, then I can clean up the links in a sensible manner.

2022-03-08 18:55 UTC, simosund commented on pping/pping.c
> +		return err;
So with other words, it's not really ready for re-review yet as I have not properly addressed your point on cleaning up the links. But before I do that I want this issue with the arguments for separate thread being on the stack of a non-main function.

2022-03-08 20:36 UTC, tohojo commented on pping/pping.c
> +		return err;
OK, sounds good. Let me know when you want me to take another look...

2022-03-10 09:10 UTC, simosund commented on pping/pping.c
> +		return err;
This function (setup_periodical_map_cleaning) should now properly destroy the links if fails. Furthermore, the links should be destroyed in the final teardown of the program (as long as they've been set up that is).

2022-03-10 09:11 UTC, simosund commented
Hi again @tohojo, I've now added two commits at the beginning of this PR that fix some errors related to the setup and teardown of the map cleaning in the userspace program. The later commits are largely the same, but builds on top of these commits to properly destroy the links as you pointed out in your comment.

2022-03-10 11:44 UTC, simosund commented on pping/pping.c
> +static volatile sig_atomic_t keep_running = 1;
If it's technically needed (as in program will stop working if it's not) I don't know. But from my understanding from ex. https://wiki.sei.cmu.edu/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers (and a bunch of stack overflow answers) is that setting the value of a non-local variables that isn't of type volatile sig_atomic_t in a singal handler is undefined behavior.

As for the second commit being a bit messy, you're right and I'm sorry about that. This particular change (changing from int to sig_atomic_t) is not really related to either the commit or even the PR as a whole, just something I fixed while working on joining together the thread at the end, but should not really have gone into the commit. 

Likewise, moving the setup of the signalhandlers is also not really related to anything anymore. Initially I needed to move them before the periodical cleaning setup due to sending a signal to the thread in order to interrupt its sleep before joining, and then I figured I might as well move it one additional step up to fix the window of vulnerability while I was at it. But then I just switched to using pthread_cancel instead (which is also probably not best practice, but avoided some issues with having to wait on the thread sleeping before being able to join)

2022-03-10 13:28 UTC, tohojo commented on pping/pping.c
> +static volatile sig_atomic_t keep_running = 1;
Alright, fair enough. And yeah, figured something like that was going on with the commit; no need to change it now, just mentioning it so you're aware for next time. Knowing how to structure commits is a skill that gets better with practice; I find it helps to be aware of it even while I'm developing the code :)

2022-03-10 13:28 UTC, tohojo approved these changes

2022-03-10 13:28 UTC, merged