Update btf example
xdp-project/bpf-examples pull request #39
Opened 2022-03-06 13:56 UTC by chenhengqi

2022-03-08 23:08 UTC, tohojo requested changes
Thank you for the fixes! Just one small nit, otherwise LGTM :)

2022-03-08 23:08 UTC, tohojo commented on BTF-playground/btf_module_read.c
> +		       err, symbol_name);
The error is not actually in `err` at this point, so this print is wrong; but it probably should just be propagated to err, so the program exit code is set correctly...

2022-03-09 01:05 UTC, chenhengqi commented on BTF-playground/btf_module_read.c
> +		       err, symbol_name);
Updated.

2022-03-09 10:45 UTC, netoptimizer commented
Thanks for improving this example.
LGTM

2022-03-09 11:00 UTC, tohojo approved these changes

2022-03-09 11:00 UTC, merged