Add samples from Linux
xdp-project/bpf-examples pull request #52
Opened 2022-08-23 10:54 UTC by magnus-karlsson

These two commits adds the two AF_XDP samples that were removed from Linux as libbpf got its xsk support deprecated. These are xdpsock and xsk_fwd. They are pretty much brought over untouched, though I have added a README file for both of them, to make using them simpler. xdpsock is now AF_XDP-example and xsk_fwd is AF_XDP-forwarding.

2022-08-24 11:44 UTC, netoptimizer commented
I'm okay with the directory naming `AF_XDP-example/` and `AF_XDP-forwarding/` for the programs.

I'm not a fan of the `xdpsock` name, but we can keep it given this came from the kernel tree.

2022-08-29 07:53 UTC, magnus-karlsson commented
Toke, any comments?

2022-08-29 08:43 UTC, tohojo requested changes
I'm OK with merging these mostly as-is, with couple of nits:

- Please convert the README files to README.org and at a minimum add headings to both of them. People will be consuming this from the github web interface, so nicely formatted README files makes things easier to read.
- Let's complete the conversion to libxdp. I.e., use the libxdp APIs for the manual load/unload of XDP programs that the utilities do, and `s/libbpf_flags/libxdp_flags/`

2022-09-20 14:05 UTC, tohojo commented on AF_XDP-forwarding/xsk_fwd.c
> +			       port_params[i].xsk_cfg.xdp_flags, NULL);
This won't actually work correctly; the XSK socket will load the XDP program with a dispatcher, but here we're just detaching the program fd from the interface, so all the pinned stuff will stay around in bpffs.

I see two options here:
- Wait for the refcnt PR to be merged into libxdp, and just get rid of this removal logic entirely
- Change this to do `xdp_multiprog__detach(xdp_multiprog__get_from_ifindex))` instead; see the `do_unload()` function in xdp-loader for the `opt->all` case.

WDYT?

2022-09-20 14:44 UTC, magnus-karlsson commented on AF_XDP-forwarding/xsk_fwd.c
> +			       port_params[i].xsk_cfg.xdp_flags, NULL);
I will change it to xdp_multiprog__detach() as I do not know when the refcnt PR will be merged. We can always remove this logic afterwards.

2022-09-22 19:43 UTC, tohojo requested changes

2022-09-22 19:43 UTC, tohojo commented on AF_XDP-example/xdpsock.c
> +	err = xdp_multiprog__detach(mp);
I don't think we should be changing this to do the full interface multiprog detach; in this example we have a reference to the xdp_prog, so just doing a regular `xdp_program__detach()` is fine (and will remove the dispatcher if it's the only program loaded).

2022-09-23 06:24 UTC, magnus-karlsson commented on AF_XDP-example/xdpsock.c
> +	err = xdp_multiprog__detach(mp);
Yes, you are correct. That is a bit too drastic. New version pushed.

2022-09-23 09:36 UTC, tohojo approved these changes

2022-09-23 09:36 UTC, merged

2022-10-11 07:53 UTC, magnus-karlsson commented
I can fix these before merging. Will submit a new version.

Thanks: Magnus

On Mon, Aug 29, 2022 at 11:43 AM Toke Høiland-Jørgensen <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I'm OK with merging these mostly as-is, with couple of nits:
>
>    - Please convert the README files to README.org and at a minimum add
>    headings to both of them. People will be consuming this from the github web
>    interface, so nicely formatted README files makes things easier to read.
>    - Let's complete the conversion to libxdp. I.e., use the libxdp APIs
>    for the manual load/unload of XDP programs that the utilities do, and
>    s/libbpf_flags/libxdp_flags/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/xdp-project/bpf-examples/pull/52#pullrequestreview-1088282236>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AASGUELOBNIBDGO7YCQCX7TV3RZ47ANCNFSM57K7TWUA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>