Fix for issue 78; veth does not support zerocopy in bind flags
xdp-project/bpf-examples pull request #79
Opened 2022-12-16 12:48 UTC by tjcw

Signed-off-by: Chris Ward <tjcw@uk.ibm.com>

2022-12-16 14:26 UTC, tohojo commented
Please write a proper commit message; also, not sure if we should just unconditionally disable the flag, or if it should be configurable. @magnus-karlsson WDYT?

2022-12-19 15:43 UTC, magnus-karlsson commented
> Please write a proper commit message; also, not sure if we should just unconditionally disable the flag, or if it should be configurable. @magnus-karlsson WDYT?

It is fine to just remove it. In this case, the bind will first try zero-copy and if that is not available, fall back to copy mode.

2023-01-02 10:59 UTC, tohojo commented
> It is fine to just remove it. In this case, the bind will first try zero-copy and if that is not available, fall back to copy mode.

Alright, cool, thanks!

2023-01-02 12:28 UTC, tohojo requested changes
The commit message still needs work:

- Drop the reference to the Github issue# form the title
- The title should describe what change is made, not the issue being fixed
- The textual description should then describe what issue is being fixed, and why that fix is OK (see Magnus' comment about falli-back).

2023-01-03 09:46 UTC, tjcw commented
@tohojo @magnus-karlsson I have made the requested changes to the PR. Can this be committed now ?

2023-01-03 09:50 UTC, tjcw commented
@magnus-karlsson in requesting a re-review from tohojo, I seem to have dropped you from the reviewer list and I cannot figure how to put you back on the list. Please review the PR anyway.

2023-01-03 15:05 UTC, tohojo commented
...you literally didn't fix any of the issues I pointed out above re: the commit message, and now you're requesting a new review? Are you deliberately trying to waste our time here? :/

2023-01-05 12:56 UTC, tohojo commented
Yeah, that's better, thanks!

2023-01-05 12:56 UTC, merged