AF_XDP-example: add multi-buffer support to xdpsock
xdp-project/bpf-examples pull request #99
Opened 2023-09-11 16:31 UTC by tirthendu-intel

* Add support for handling multi-buffer packets.
* Add a new CLI option to enable frag support.
* xdpsock_kern.c is modified to use num_socks as updated by userspace application.
* MAX_PKT_SIZE is set as 9728 as supported by many NICs.
* xdpsock_kern.o is loaded for both frags and shared uemem cases.

2023-09-15 09:31 UTC, magnus-karlsson requested changes

2023-09-21 05:34 UTC, tirthendu-intel commented on AF_XDP-example/xdpsock.c
> +#define MAX_PKT_SIZE 9728 /* Max frame size supported by many NICs */
The largest packet that I can receive for i40e is of size 9728B. Also, this is mentioned as the largest frame size in i40e driver.

2023-09-21 05:35 UTC, tirthendu-intel commented on AF_XDP-example/xdpsock.c
> +	len -= copy_len;
|Yes, we are setting default data. Also, user can pass their own using CLI option.

2023-09-21 05:36 UTC, tirthendu-intel commented on AF_XDP-example/xdpsock.c
> -
ACK.

2023-09-21 05:36 UTC, tirthendu-intel commented on AF_XDP-example/xdpsock.c
> +	xsk->ring_stats.rx_npkts += eop_cnt;
ACK. Will add.

2023-09-21 05:36 UTC, tirthendu-intel commented on AF_XDP-example/xdpsock.c
> +
ACK

2023-09-21 05:36 UTC, tirthendu-intel commented on AF_XDP-example/xdpsock.c
> +
ACK

2023-09-26 07:52 UTC, magnus-karlsson approved these changes
Looks good Tirtha. Thanks!

2023-09-26 08:17 UTC, merged